### ISSUE TITLE
Version 2.30 breaks babel-preset-env@1.7.0

### ISSUE THREAD

**Issue by tjkorona** [clarkbw/jest-localstorage-mock#93]
We currently use babel-preset-env@1.7.0 in our project along with jest-localstorage-mock@2.2.0.  Version 2.3.0 does not appear to work with babel-reset-env@1.7.0, we are receiving the following error:

Couldn't find preset "@babel/preset-env" relative to directory "C:\\source\\ohiohealth\\node_modules\\jest-localstorage-mock"

      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)

When we revert back to version 2.2.0 everything works.

**Comment by clarkbw** [comment]
🤔 

Thanks for reporting this!  I'll take a look and see what I can find out.

**Comment by DavideDaniel** [comment]
This is the problem - not sure why it's being invoked in others' test env though. https://github.com/clarkbw/jest-localstorage-mock/blob/master/package.json#L62

**Comment by clarkbw** [comment]
Update to version 2.4.0 https://github.com/clarkbw/jest-localstorage-mock/releases/tag/v2.4.0 and let me know if the problem persists.  Thanks!  

Sorry for the long delay, I've been away on family leave.
